package easyzhang;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.city_id
     *
     * @mbg.generated Tue Jul 10 13:02:25 CST 2018
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.city_name
     *
     * @mbg.generated Tue Jul 10 13:02:25 CST 2018
     */
    private String cityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.city_id
     *
     * @return the value of t_city.city_id
     *
     * @mbg.generated Tue Jul 10 13:02:25 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.city_id
     *
     * @param cityId the value for t_city.city_id
     *
     * @mbg.generated Tue Jul 10 13:02:25 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_city.city_name
     *
     * @return the value of t_city.city_name
     *
     * @mbg.generated Tue Jul 10 13:02:25 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_city.city_name
     *
     * @param cityName the value for t_city.city_name
     *
     * @mbg.generated Tue Jul 10 13:02:25 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }
}