package easyzhang;

public class StudentPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_name
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    private String studentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_name
     *
     * @return the value of t_student.student_name
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_name
     *
     * @param studentName the value for t_student.student_name
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }
}