package easyzhang;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    long countByExample(StudentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int deleteByExample(StudentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int insert(StudentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int insertSelective(StudentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    List<StudentPo> selectByExample(StudentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    StudentPo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") StudentPo record, @Param("example") StudentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int updateByExample(@Param("record") StudentPo record, @Param("example") StudentPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int updateByPrimaryKeySelective(StudentPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Fri Jun 21 10:42:18 CST 2019
     */
    int updateByPrimaryKey(StudentPo record);
}
